apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: database1-postgres-ingress
  namespace: database
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"  # Specifies that the backend uses TCP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    # Disables HTTP to HTTPS redirection
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}  # Secret containing TLS certificate and key
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
    {{- end }}
