apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-db-initializer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
  labels:
    app: {{ .Release.Name }}-db-init
spec:
  template:
    spec:
      containers:
      - name: init-database
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db-password
        - name: PGPASSWORD  # This is crucial for `psql` commands to automatically use the password
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db-password
        - name: USER_SUBSCRIPTION_DB
          value: "{{ .Values.global.postgresql.auth.databases[0].name }}"
        - name: USER_SUBSCRIPTION_DB_USER
          value: "{{ .Values.global.postgresql.auth.databases[0].user }}"
        - name: USER_SUBSCRIPTION_DB_PASSWORD
          value: "{{ .Values.global.postgresql.auth.databases[0].password }}"
        - name: STOCK_DATA_DB
          value: "{{ .Values.global.postgresql.auth.databases[1].name }}"
        - name: STOCK_DATA_DB_USER
          value: "{{ .Values.global.postgresql.auth.databases[1].user }}"
        - name: STOCK_DATA_DB_PASSWORD
          value: "{{ .Values.global.postgresql.auth.databases[1].password }}"
        command:
          - "sh"
          - "-c"
          - |
            echo "Starting database and user initialization"

            until pg_isready -h {{ .Release.Name }}-postgres -p 5432 -U "$POSTGRES_USER"; do
              >&2 echo "PostgreSQL is unavailable - sleeping"
              sleep 5
            done

            echo "Creating databases and users if not already present..."

            # Check if the databases exist, create if they don't
            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$USER_SUBSCRIPTION_DB'" | grep -q 1 || \
              psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "CREATE DATABASE \"$USER_SUBSCRIPTION_DB\""

            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$STOCK_DATA_DB'" | grep -q 1 || \
              psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "CREATE DATABASE \"$STOCK_DATA_DB\""

            # Create users for each database if not already present
            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$USER_SUBSCRIPTION_DB_USER') THEN CREATE ROLE \"$USER_SUBSCRIPTION_DB_USER\" WITH LOGIN PASSWORD '$USER_SUBSCRIPTION_DB_PASSWORD'; END IF; END \$\$;"
            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$STOCK_DATA_DB_USER') THEN CREATE ROLE \"$STOCK_DATA_DB_USER\" WITH LOGIN PASSWORD '$STOCK_DATA_DB_PASSWORD'; END IF; END \$\$;"

            # Grant privileges to the new users
            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON DATABASE \"$USER_SUBSCRIPTION_DB\" TO \"$USER_SUBSCRIPTION_DB_USER\";"
            psql -h {{ .Release.Name }}-postgres -U "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON DATABASE \"$STOCK_DATA_DB\" TO \"$STOCK_DATA_DB_USER\";"

            # Create tables in the user subscription database
            psql -h {{ .Release.Name }}-postgres -U "$USER_SUBSCRIPTION_DB_USER" -d "$USER_SUBSCRIPTION_DB" -c "$CREATE_USER_SUBSCRIPTION_DB_SQL"

            # Create tables in the stock data database
            psql -h {{ .Release.Name }}-postgres -U "$STOCK_DATA_DB_USER" -d "$STOCK_DATA_DB" -c "$CREATE_STOCK_DATA_DB_SQL"

            echo "Database and user initialization complete."
      restartPolicy: OnFailure
  backoffLimit: 4
