apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-password: U3Ryb25nU0Ajc3cwcmQ=  # Base64 encoded password ('StrongS@#sw0rd')
