gravitee:
  gateway:
    enabled: true
    image:
      repository: graviteeio/apim-gateway
      tag: 3.10.4
    service:
      type: ClusterIP

  management:
    type: jdbc # Specify that you are using a JDBC database like PostgreSQL instead of the default MongoDB.

  database:
    type: postgresql

    jdbc:
      enabled: true
      host: database1-postgres.database.svc.cluster.local
      port: 5432
      name: user_subscription_db
      username: user_subscription_user
      password:
        existingSecret: gravitee-db-secret
        existingSecretKey: db-password

mongodb:
  enabled: false

elasticsearch:
  enabled: false
