gravitee:
  replicaCount: 2  # Number of replicas for your deployment

externalDatabase:
  host: postgres-service.database.svc.cluster.local
  port: 5432
  database: user_subscription_db
  user: user_subscription_user
  password:
    existingSecret: postgres-secret  # The name of the secret storing the database password
    existingSecretKey: db-password   # The key of the password inside the secret
