global:
  storageClass: fast-ssd

postgresql:
  enabled: false # Disable internal PostgreSQL since we're using an existing DB.

externalDatabase:
  host: postgres-service.database.svc.cluster.local # Use the correct namespace/service
  port: 5432
  user: gravitee_user
  password:
    existingSecret: postgres-secret
    existingSecretKey: db-password
  database: user_subscription_db

gravitee:
  gateway:
    service:
      type: ClusterIP
  replicaCount: 2
