global:
  storageClass: fast-ssd

postgresql:
  enabled: false # Disable internal PostgreSQL since we're using an existing DB.

externalDatabase:
  host: database1-postgres.database.svc.cluster.local
  port: 5432
  database: user_subscription_db
  user: user_subscription_user
  password:
    existingSecret: gravitee-db-secret  # The name of the secret storing the database password
    existingSecretKey: db-password  

gravitee:
  gateway:
    service:
      type: ClusterIP
  replicaCount: 2

mongodb:
  enabled: false

elasticsearch:
  enabled: false
