gravitee:
  gateway:
    enabled: true
    image:
      repository: graviteeio/apim-gateway
      tag: 3.10.4
    service:
      type: ClusterIP

  management:
    type: postgresql
    jdbc:
      driver: https://jdbc.postgresql.org/download/postgresql-42.2.23.jar
      url: jdbc:postgresql://postgres-apim-postgresql:5432/graviteeapim
      username: postgres
      password: P@ssw0rd

  database:
    type: postgresql
    jdbc:
      enabled: true
      host: database1-postgres.database.svc.cluster.local
      port: 5432
      name: user_subscription_db
      username: user_subscription_user
      password:
        existingSecret: gravitee-db-secret
        existingSecretKey: db-password

mongodb:
  enabled: false

elasticsearch:
  enabled: false
