apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: user-management
  labels:
    app: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:{{ .Chart.appVersion }}
        ports:
          - containerPort: 8080
        env:
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADDR
            value: {{ .Values.externalDatabase.host }}
          - name: DB_PORT
            value: "{{ .Values.externalDatabase.port }}"
          - name: DB_DATABASE
            value: {{ .Values.externalDatabase.database }}
          - name: DB_USER
            value: {{ .Values.externalDatabase.user }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.password.existingSecret }}
                key: {{ .Values.externalDatabase.password.existingSecretKey }}
