apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: user-management
type: Opaque
data:
  db-password: <base64_encoded_password>
  keycloak-admin-password: <base64_encoded_password>
