apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | lower }}
spec:
  replicas: {{ .Values.gravitee.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name | lower }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | lower }}
    spec:
      containers:
        - name: gravitee
          image: graviteeio/apim-gateway:3.10.4
          ports:
            - containerPort: 8082
          env:
            - name: GRAVITEE_DATABASE_TYPE
              value: postgresql
            - name: GRAVITEE_DATABASE_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: GRAVITEE_DATABASE_PORT
              value: "{{ .Values.externalDatabase.port }}"
            - name: GRAVITEE_DATABASE_NAME
              value: {{ .Values.externalDatabase.database }}
            - name: GRAVITEE_DATABASE_USERNAME
              value: {{ .Values.externalDatabase.user }}
            - name: GRAVITEE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.password.existingSecret }}
                  key: {{ .Values.externalDatabase.password.existingSecretKey }}
