apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee
  namespace: user-management
  labels:
    app: gravitee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gravitee
  template:
    metadata:
      labels:
        app: gravitee
    spec:
      containers:
        - name: gravitee
          image: graviteeio/apim-gateway:3.10.4
          ports:
            - containerPort: 8082
          env:
            - name: GRAVITEE_DATABASE_TYPE
              value: postgresql
            - name: GRAVITEE_DATABASE_HOST
              value: database1-postgres.database.svc.cluster.local
            - name: GRAVITEE_DATABASE_PORT
              value: "5432"
            - name: GRAVITEE_DATABASE_NAME
              value: user_subscription_db
            - name: GRAVITEE_DATABASE_USERNAME
              value: user_subscription_user
            - name: GRAVITEE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gravitee-db-secret
                  key: db-password
          volumeMounts:
            - name: gravitee-override
              mountPath: /gravitee/config/gravitee-override.yaml
              subPath: gravitee-override.yaml
      volumes:
        - name: gravitee-override
          configMap:
            name: gravitee-config
