apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitee
  namespace: user-management
  labels:
    app: gravitee
spec:
  replicas: {{ .Values.gravitee.replicaCount }}
  selector:
    matchLabels:
      app: gravitee
  template:
    metadata:
      labels:
        app: gravitee
    spec:
      containers:
      - name: gravitee-gateway
        image: graviteeio/apim-gateway:{{ .Chart.appVersion }}
        ports:
          - containerPort: 8082
        env:
          - name: GRAVITEE_DATABASE_TYPE
            value: postgresql
          - name: GRAVITEE_DATABASE_HOST
            value: {{ .Values.externalDatabase.host }}
          - name: GRAVITEE_DATABASE_PORT
            value: "{{ .Values.externalDatabase.port }}"
          - name: GRAVITEE_DATABASE_NAME
            value: {{ .Values.externalDatabase.database }}
          - name: GRAVITEE_DATABASE_USERNAME
            value: {{ .Values.externalDatabase.user }}
          - name: GRAVITEE_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.password.existingSecret }}
                key: {{ .Values.externalDatabase.password.existingSecretKey }}
