apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.gravitee.gateway.service.type }}
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ .Release.Name }}
