apiVersion: v1
kind: Service
metadata:
  name: gravitee-gateway
  namespace: user-management
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: gravitee
  type: {{ .Values.gravitee.gateway.service.type }}
