replicaCount: 1
postgres:
  image: "postgres:13"
  database: "mydatabase"
  username: "admin"
  password: "password123" 
  storageClass: fast-ssd
  storage: 5Gi

service:
  type: ClusterIP

image:
  pullPolicy: IfNotPresent
