postgres:
  image: "postgres:13"
  database: "mydatabase"
  username: "admin"
  password: "password123"
  storageClass: fast-ssd
  storage: 5Gi

service:
  type: ClusterIP

image:
  pullPolicy: IfNotPresent

global:
  postgresql:
    auth:
      databases:
        user_subscription_db:
          name: user_subscription_db
          user: user_subscription_user
          password: subscription_password
        stock_data_db:
          name: stock_data_db
          user: stock_data_user
          password: stock_password

