postgres:
  image: "postgres:13"
  database: "mydatabase"
  username: "admin"
  password: "password123"
  storageClass: fast-ssd
  storage: 5Gi

service:
  name: database1-postgres
  type: NodePort  # Change to NodePort for external access (Options: ClusterIP, LoadBalancer, NodePort)
  port: 5432
  nodePort: 30036 # NodePort to expose (range: 30000-32767)

image:
  pullPolicy: IfNotPresent

global:
  postgresql:
    auth:
      databases:
        user_subscription_db:
          name: user_subscription_db
          user: user_subscription_user
          password: subscription_password
        stock_data_db:
          name: stock_data_db
          user: stock_data_user
          password: stock_password

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"
  hosts:
    - host: database.home.com
  tlsSecretName: postgres-tls
