apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gravitee
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/XPKX00/Stock_SaaS'
    targetRevision: HEAD
    path: Helm/API/gravitee
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  releaseName: gravitee # Ensure release name is lowercase
  namespace: user-management
